### ISSUE TITLE
status 504 errors on connect.  Commands seem to work?

### ISSUE THREAD

**Issue by lzthqx** [BigThunderSR/onstar2mqtt#135]
Error as follows:

`error: Error {"error":{"error":{"message":"Request Failed with status 504 - Gateway Timeout","request":{"method":"POST"},"response":{"data":"","headers":{"cache-control":"no-store","connection":"keep-alive","content-length":"0","date":"Tue, 05 Mar 2024 20:06:18 GMT","pragma":"no-cache","request-context":"appId=cid-v1:a7e19842-5b19-4b47-a9cf-85cc6e87a746"},"status":504,"statusText":"Gateway Timeout"},"stack":"Error: Request Failed with status 504 - Gateway Timeout\n    at RequestService.<anonymous> (/app/node_modules/onstarjs/dist/index.cjs:588:32)\n    at Generator.throw (<anonymous>)\n    at rejected (/app/node_modules/onstarjs/dist/index.cjs:27:65)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)"}},"timestamp":"2024-03-05 13:06:18"}
`
Able to confirm connectivity is working fine, dns resolution etc from inside the container.  It was working for quite a while until a recent update of the image. Perhaps I'm missing something?

**Comment by lzthqx** [comment]
Thanks so much for the quick reply! I was concerned this was the issue, but wanted to eliminate the possibility I had missed a step somewhere.  Thanks for all your efforts!
