### ISSUE TITLE
Diesel Exhaust Fluid (DEF) state 'Green' update needed

### ISSUE THREAD

**Issue by almoney** [BigThunderSR/onstar2mqtt#278]
I have a Diesel Escalade in use and it generates this exception.  Is there a dictionary that shows this sensor is a text string I can update?  (I have 4 vehicles that are working well with the 2 in Home Assistant and 2 more in Docker Containers.

 Logger: homeassistant.components.mqtt.models
Source: components/mqtt/models.py:383
integration: MQTT (documentation, issues)
First occurred: August 11, 2024 at 6:38:13 AM (81 occurrences)
Last logged: 6:38:26 AM

Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_on, topic: 'homeassistant/**VIN**/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_2_on, topic: 'homeassistant/**VIN**/available' with payload: b'true'
Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_amount, topic: **'homeassistant/VIN/available'** with payload: b'true'
Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_capacity, topic: **'homeassistant/VIN/available'** with payload: b'true'
Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_level_in_gal, topic: 'homeassistant/VIN/available' with payload: b'true'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 653, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Green'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 383, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 655, in state
    raise ValueError(
ValueError: Sensor sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status has device class 'None', state class 'measurement' unit 'NA' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Green' (<class 'str'>)

**Comment by almoney** [comment]
I started the container with debug.  I generated the same error above in Home Assistant MQTT.  Log attached.
[onstar2mqttEscaladeESV_logs.txt](https://github.com/user-attachments/files/16625176/onstar2mqttEscaladeESV_logs.txt)

**Comment by almoney** [comment]
Ok, I'm not available to do that until next week.

**Comment by almoney** [comment]
Thank you!Jeff AlmoneyOn Aug 15, 2024, at 8:54 AM, BigThunderSR ***@***.***> wrote:﻿
@almoney, the information I need to make the necessary code changes is not in the log you provided because the vehicle is in hibernation and didn't generate any diagnostic data. Could you please provide a sanitized extract of only the following fields when the vehicle has been brought out of hibernation and provides diagnostic data? I don't need anything else besides these fields/sections:
"Diagnostic request status"
"Diagnostic request response"

**Comment by almoney** [comment]
I started the vehicle and these are the responses: (let me know if you would like more info.)

info: Requesting diagnostics {"timestamp":"2024-08-20 22:39:49"}
debug: GetSupported: ENGINE COOLANT TEMP,ENGINE RPM,TIRE PRESSURE,OIL LIFE,LIFETIME FUEL ECON,DIESEL WARNING,FUEL TANK INFO,ENGINE AIR FILTER MONITOR STATUS,HOTSPOT CONFIG,LIFETIME FUEL USED,ODOMETER,HOTSPOT STATUS,VEHICLE RANGE {"timestamp":"2024-08-20 22:39:49"}
info: Diagnostic request status {"status":"success","timestamp":"2024-08-20 22:40:19"}
debug: Diagnostic request response: {"stats":["DIESEL WARNING:\n  EXHST FL LEVL WARN IND: 1LVL\n  EXHST FL LEVL WARN STATUS: GreenNA\n  EXHST PART FLTR WARN ON: FALSENA\n  EXHST PART FLTR WARN2 ON: FALSENA\n","ENGINE AIR FILTER MONITOR STATUS:\n  ENGINE AIR FILTER MONITOR STATUS: 51.0%\n","ENGINE COOLANT TEMP:\n  ENGINE COOLANT TEMP: 40.00°C\n  ENGINE COOLANT TEMP F: 104°F\n","ENGINE RPM:\n  ENGINE RPM: 0.000RPM\n","FUEL TANK INFO:\n  FUEL AMOUNT: 105.45L\n  FUEL CAPACITY: 105.88L\n  FUEL LEVEL: 99.6%\n  FUEL LEVEL IN GAL: 105.45L\n  FUEL AMOUNT GAL: 27.9gal\n  FUEL CAPACITY GAL: 28gal\n  FUEL LEVEL IN GAL GAL: 27.9gal\n","HOTSPOT CONFIG:\n","HOTSPOT STATUS:\n","LIFETIME FUEL ECON:\n  LIFETIME FUEL ECON: 10.99km/L\n  LIFETIME FUEL ECON MPG: 25.9mpg\n","LIFETIME FUEL USED:\n  LIFETIME FUEL USED: 4739.72L\n  LIFETIME FUEL USED GAL: 1252.1gal\n","ODOMETER:\n  ODOMETER: 52056.64km\n  ODOMETER MI: 32346.5mi\n","OIL LIFE:\n  OIL LIFE: 20.7%\n","TIRE PRESSURE:\n  TIRE PRESSURE LF: 236.0kPa\n  TIRE PRESSURE LR: 252.0kPa\n  TIRE PRESSURE PLACARD FRONT: 250.0kPa\n  TIRE PRESSURE PLACARD REAR: 250.0kPa\n  TIRE PRESSURE RF: 256.0kPa\n  TIRE PRESSURE RR: 256.0kPa\n  TIRE PRESSURE LF PSI: 34.2psi\n  TIRE PRESSURE LR PSI: 36.5psi\n  TIRE PRESSURE PLACARD FRONT PSI: 36.3psi\n  TIRE PRESSURE PLACARD REAR PSI: 36.3psi\n  TIRE PRESSURE RF PSI: 37.1psi\n  TIRE PRESSURE RR PSI: 37.1psi\n","VEHICLE RANGE:\n  GAS RANGE: 1144.26km\n  GAS RANGE MI: 711mi\n"],"timestamp":"2024-08-20 22:40:19"}

**Comment by almoney** [comment]
I did a pull for latest and restarted the container for the Diesel.  bigthundersr/onstar2mqtt:latest in Portainer.  Is this what you wanted?  This is the log minus the VINs in my HA log:

Logger: homeassistant.components.mqtt.models
Source: components/mqtt/models.py:383
integration: MQTT (documentation, issues)
First occurred: August 11, 2024 at 6:38:13 AM (195 occurrences)
Last logged: 10:43:38 PM

Exception raised while updating state of sensor.2022_gmc_hummer_ev_high_voltage_battery_preconditioning_status, topic: 'homeassistant/sensor/VIN/high_voltage_battery_preconditioning_status/state' with payload: b'{"high_voltage_battery_preconditioning_status":"ACTIVE","high_voltage_battery_preconditioning_status_message":"na"}'
Exception raised while updating state of sensor.2022_gmc_hummer_ev_high_voltage_battery_preconditioning_status, topic: 'homeassistant/sensor/VIN/high_voltage_battery_preconditioning_status/state' with payload: b'{"high_voltage_battery_preconditioning_status":"INACTIVE","high_voltage_battery_preconditioning_status_message":"na"}'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_2_on, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_on, topic: 'homeassistant/VIN/available' with payload: b'true'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 653, in state
    numerical_value = float(value)  # type:ignore[arg-type]
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'Green'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 383, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 655, in state
    raise ValueError(
ValueError: Sensor sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status has device class 'None', state class 'measurement' unit 'NA' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Green' (<class 'str'>)

**Comment by almoney** [comment]
I used mqtt explorer to delete the entities and developer tools purge entities. They were recreated.  This is the new error:

Logger: homeassistant.components.mqtt.models
Source: components/mqtt/models.py:383
integration: MQTT (documentation, issues)
First occurred: 6:32:53 AM (12 occurrences)
Last logged: 11:19:11 AM

Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_amount, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_capacity, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_2_on, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_on, topic: 'homeassistant/VIN/available' with payload: b'true'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 648, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'FALSE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 651, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'FALSE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 383, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 655, in state
    raise ValueError(
ValueError: Sensor sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_2_on has device class 'None', state class 'None' unit 'NA' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'FALSE' (<class 'str'>)

**Comment by almoney** [comment]
After the latest update I see this in the dashboard: 
![image](https://github.com/user-attachments/assets/4c0c20bf-b72b-4180-b29c-611fece3d6f4)
and this is in the logs: (This is like tire pressure GREEN status that we need to model?)
Logger: homeassistant.components.mqtt.models
Source: components/mqtt/models.py:383
integration: MQTT (documentation, issues)
First occurred: August 21, 2024 at 6:32:53 AM (31 occurrences)
Last logged: 7:40:01 AM

Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_2_on, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_level_in_gal, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_amount, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2020_cadillac_ct6_awd_super_cruise_fuel_capacity, topic: 'homeassistant/VIN/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status, topic: 'homeassistant/VIN/available' with payload: b'true'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 648, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'FALSE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 651, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'FALSE'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 383, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1007, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1133, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1068, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 655, in state
    raise ValueError(
ValueError: Sensor sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_part_fltr_warn_2_on has device class 'None', state class 'None' unit 'NA' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'FALSE' (<class 'str'>)

**Comment by almoney** [comment]
I will take another look tomorrow.  I am not with the Diesel right now.

**Comment by almoney** [comment]
This is what I see in MQTT Explorer: 
{"exhst_fl_levl_warn_ind":1,"exhst_fl_levl_warn_ind_message":"na","exhst_fl_levl_warn_status":"Green","exhst_fl_levl_warn_status_message":"na","exhst_part_fltr_warn_on":"FALSE","exhst_part_fltr_warn_on_message":"na","exhst_part_fltr_warn2_on":"FALSE","exhst_part_fltr_warn2_on_message":"na"}

This is the dashboard:

![image](https://github.com/user-attachments/assets/c774c017-b3b9-4ff1-8965-7d80a6b4b605)

Interested to learn the process.  Is the data typed somewhere that we need to update?

**Comment by almoney** [comment]
> @almoney, did the latest update work?

Sorry Ihave not been able to run the Escalade yet. Will report on Thursday.

**Comment by almoney** [comment]
This is the debug log:

2024-09-09T20:47:35.821281571Z debug: Diagnostic request response: {"stats":["DIESEL WARNING:\n  EXHST FL LEVL WARN IND: 1LVL\n  EXHST FL LEVL WARN STATUS: GreenNA\n  EXHST PART FLTR WARN ON: FALSENA\n  EXHST PART FLTR WARN2 ON: FALSENA\n","ENGINE AIR FILTER MONITOR STATUS:\n  ENGINE AIR FILTER MONITOR STATUS: 50.0%\n","ENGINE COOLANT TEMP:\n  ENGINE COOLANT TEMP: 39.00°C\n  ENGINE COOLANT TEMP F: 102°F\n","ENGINE RPM:\n  ENGINE RPM: 900.000RPM\n","FUEL TANK INFO:\n  FUEL AMOUNT: 105.88L\n  FUEL CAPACITY: 105.88L\n  FUEL LEVEL: 100.0%\n  FUEL LEVEL IN GAL: 105.88L\n  FUEL AMOUNT GAL: 28gal\n  FUEL CAPACITY GAL: 28gal\n  FUEL LEVEL IN GAL GAL: 28gal\n","HOTSPOT CONFIG:\n","HOTSPOT STATUS:\n","LIFETIME FUEL ECON:\n  LIFETIME FUEL ECON: 10.99km/L\n  LIFETIME FUEL ECON MPG: 25.9mpg\n","LIFETIME FUEL USED:\n  LIFETIME FUEL USED: 4739.92L\n  LIFETIME FUEL USED GAL: 1252.2gal\n","ODOMETER:\n  ODOMETER: 52056.64km\n  ODOMETER MI: 32346.5mi\n","OIL LIFE:\n  OIL LIFE: 17.2%\n","TIRE PRESSURE:\n  TIRE PRESSURE LF: 236.0kPa\n  TIRE PRESSURE LR: 252.0kPa\n  TIRE PRESSURE PLACARD FRONT: 250.0kPa\n  TIRE PRESSURE PLACARD REAR: 250.0kPa\n  TIRE PRESSURE RF: 256.0kPa\n  TIRE PRESSURE RR: 244.0kPa\n  TIRE PRESSURE LF PSI: 34.2psi\n  TIRE PRESSURE LR PSI: 36.5psi\n  TIRE PRESSURE PLACARD FRONT PSI: 36.3psi\n  TIRE PRESSURE PLACARD REAR PSI: 36.3psi\n  TIRE PRESSURE RF PSI: 37.1psi\n  TIRE PRESSURE RR PSI: 35.4psi\n","VEHICLE RANGE:\n  GAS RANGE: 1128.17km\n  GAS RANGE MI: 701mi\n"],"timestamp":"2024-09-09 20:47:35"}

The sensor still has Unknown as the status for the Exhst Fl Levl Warn Status.  I think is should show GREEN.

Logger: homeassistant.components.mqtt.models
Source: components/mqtt/models.py:366
integration: MQTT (documentation, issues)
First occurred: September 7, 2024 at 6:19:27 AM (38 occurrences)
Last logged: 4:47:36 PM

Exception raised while updating state of sensor.2022_gmc_hummer_ev_high_voltage_battery_preconditioning_status, topic: 'homeassistant/sensor/VIN1/high_voltage_battery_preconditioning_status/state' with payload: b'{"high_voltage_battery_preconditioning_status":"DISABLED","high_voltage_battery_preconditioning_status_message":"na"}'
Exception raised while updating state of sensor.2022_gmc_hummer_ev_high_voltage_battery_preconditioning_status, topic: 'homeassistant/sensor/VIN1/high_voltage_battery_preconditioning_status/state' with payload: b'{"high_voltage_battery_preconditioning_status":"INACTIVE","high_voltage_battery_preconditioning_status_message":"na"}'
Exception raised while updating state of sensor.2022_gmc_hummer_ev_cabin_preconditioning_request, topic: 'homeassistant/sensor/VIN1/cabin_preconditioning_request/state' with payload: b'{"cabin_preconditioning_request":"INACTIVE","cabin_preconditioning_request_message":"na"}'
Exception raised while updating state of sensor.2022_gmc_hummer_ev_cabin_preconditioning_request, topic: 'homeassistant/sensor/VIN1/cabin_preconditioning_request/state' with payload: b'{"cabin_preconditioning_request":"NO_ACTION","cabin_preconditioning_request_message":"na"}'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status, topic: 'homeassistant/sensor/VIN2/diesel_warning/state' with payload: b'{"exhst_fl_levl_warn_ind":1,"exhst_fl_levl_warn_ind_message":"na","exhst_fl_levl_warn_status":"Green","exhst_fl_levl_warn_status_message":"na","exhst_part_fltr_warn_on":"FALSE","exhst_part_fltr_warn_on_message":"na","exhst_part_fltr_warn2_on":"FALSE","exhst_part_fltr_warn2_on_message":"na"}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 657, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'NO_ACTION'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 660, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'NO_ACTION'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 366, in process_write_state_requests
    entity.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1005, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1130, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1067, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1011, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 664, in state
    raise ValueError(
ValueError: Sensor sensor.2022_gmc_hummer_ev_cabin_preconditioning_request has device class 'None', state class 'measurement' unit 'None' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'NO_ACTION' (<class 'str'>)

**Comment by almoney** [comment]
> Sorry about the delay on this. Unfortunately, if we don't get past the latest key issue which we discovered yesterday, then all of this becomes moot, so I'm going to pause on this until we have a solution to the key issue.

Where is the issue documented?

**Comment by almoney** [comment]
@BigThunderSR, I have installed the latest version (I run Watchtower hourly). The backend has been intermittent—I mostly get 504 errors even after a key cycle. Once it updates, I will check to see if HA is still complaining.

**Comment by almoney** [comment]
@BigThunderSR the 504's continue but 2 sensors are corrected: 

![Image](https://github.com/user-attachments/assets/5d3a77be-fb7d-4d7b-9a43-29086025685c)

Warn status should be "GREEN"

This is in the log:

Logger: homeassistant.components.mqtt.models
Source: components/mqtt/models.py:366
integration: MQTT (documentation, issues)
First occurred: April 4, 2025 at 1:47:33 PM (140 occurrences)
Last logged: 7:37:40 AM

Exception raised while updating state of sensor.2024_cadillac_lyriq_super_cruise_scheduled_cabin_precondtion_custom_set_req_active, topic: 'homeassistant/1GYKPSRL8RZ125280/available' with payload: b'true'
Exception raised while updating state of sensor.2024_cadillac_lyriq_super_cruise_cabin_preconditioning_request, topic: 'homeassistant/1GYKPSRL8RZ125280/available' with payload: b'true'
Exception raised while updating state of sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status, topic: 'homeassistant/1GYS4RKTXNR243952/available' with payload: b'true'
Exception raised while updating state of sensor.2024_cadillac_lyriq_super_cruise_veh_not_in_home_loc, topic: 'homeassistant/sensor/1GYKPSRL8RZ125280/target_charge_level_settings/state' with payload: b'{"loc_based_charging_home_loc_stored":true,"loc_based_charging_home_loc_stored_message":"na","projected_ev_range_general_away_target_charge_set":538.984,"projected_ev_range_general_away_target_charge_set_message":"na","veh_in_home_location":false,"veh_in_home_location_message":"na","veh_location_status_invalid":false,"veh_location_status_invalid_message":"na","veh_not_in_home_loc":true,"veh_not_in_home_loc_message":"na","projected_ev_range_general_away_target_charge_set_mi":334.9,"projected_ev_range_general_away_target_charge_set_mi_message":"na"}'
Exception raised while updating state of sensor.2024_cadillac_lyriq_super_cruise_veh_in_home_location, topic: 'homeassistant/sensor/1GYKPSRL8RZ125280/target_charge_level_settings/state' with payload: b'{"loc_based_charging_home_loc_stored":true,"loc_based_charging_home_loc_stored_message":"na","projected_ev_range_general_away_target_charge_set":538.984,"projected_ev_range_general_away_target_charge_set_message":"na","veh_in_home_location":false,"veh_in_home_location_message":"na","veh_location_status_invalid":false,"veh_location_status_invalid_message":"na","veh_not_in_home_loc":true,"veh_not_in_home_loc_message":"na","projected_ev_range_general_away_target_charge_set_mi":334.9,"projected_ev_range_general_away_target_charge_set_mi_message":"na"}'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 640, in state
    numerical_value = float(value)  # type:ignore[arg-type]
ValueError: could not convert string to float: 'Green'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/models.py", line 366, in process_write_state_requests
    entity.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.2022_cadillac_escalade_esv_diesel_super_cruise_exhst_fl_levl_warn_status has device class 'None', state class 'None' unit 'NA' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'Green' (<class 'str'>)

**Comment by almoney** [comment]
@BigThunderSR, I have restarted and will let you know what we see after I get past the 504's.

**Comment by almoney** [comment]
I finally got a poll and DEF is now Green. Thank you!

**Comment by almoney** [comment]
I am closing this issue, but I want to share the updated display:

![Image](https://github.com/user-attachments/assets/303ad714-6ce5-416d-bcd0-f2feca84580c)
